name: "Tests"

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    name: "ubuntu-latest / PHP ${{ matrix.php-version }}"
    runs-on: 'ubuntu-latest'
    continue-on-error: false

    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3' ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          extensions: "intl, mbstring, pdo_sqlite, zip"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: "Set composer cache directory"
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: "Cache composer"
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install dependencies"
        run: composer install --ansi --no-interaction --no-progress

      - name: "Install lower versions of packages for PHP 8.1
        run: |
          if [ "${{ matrix.php-version }}" == "8.1" ]; then
            composer require "symfony/dependency-injection:^6.0 symfony/framework-bundle:^6.0 symfony/http-foundation:^6.0 symfony/http-kernel:^6.0 symfony/serializer:^6.0 symfony/property-access:^6.0";
          fi

      - name: "Run Pest2 test suits"
        run: vendor/bin/pest